name: Build master

on:
  #push:
    #branches:
      #- master
  # trigger on all PRs against master
  #pull_request:
    #branches:
      #- master
  # allow manual dispatches
  workflow_dispatch:

jobs:
  builder:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #builder: ["windows_master", "macos_master", "linux_master"]
        builder: ["linux_master"]
        include:
          #- builder: "windows_master"
            #os: "windows-2019"
            #branch: "master"
          #- builder: "macos_master"
            #os: "macos-10.15"
            #branch: "master"
          - builder: "linux_master"
            os: "ubuntu-18.04"
            branch: "master"
    steps:
      - name: Cache lib folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/lib
          key: ${{ matrix.builder }}-lib-${{ github.ref }}-${{ runner.OS }}
          restore-keys: |
            ${{ matrix.builder }}-lib-${{ github.ref }}
            ${{ matrix.builder }}-lib
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: worker_preparation
        run: mkdir -p ${{ github.workspace }}/build

      # Required for CMake options:
      # WITH_X11_XINPUT, WITH_X11_XF86VMODE, WITH_X11_XFIXES, WITH_X11_ALPHA, OPENGL_INCLUDE_DIR respectively
      - name: worker_preparation for Ubuntu
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04'
        run: sudo apt-get install -y libxi-dev libxxf86vm-dev libxfixes-dev libxrender-dev libgl1-mesa-dev

      - name: Checkout Blender ${{ matrix.branch }}
        uses: actions/checkout@v2
        with:
          path: upbge.git
          fetch-depth: 0
          submodules: false

      - name: submodules and libraries update
        working-directory: ${{ github.workspace }}/build
        run: python ../upbge.git/build_files/buildbot/worker_update.py ${{ matrix.builder }} ${{ matrix.branch }}

      - name: compile
        working-directory: ${{ github.workspace }}/build
        run: python ../upbge.git/build_files/buildbot/worker_compile.py ${{ matrix.builder }} ${{ matrix.branch }}

      - name: package
        working-directory: ${{ github.workspace }}/build
        run: python ../upbge.git/build_files/buildbot/worker_pack.py ${{ matrix.builder }} ${{ matrix.branch }}

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: blender-${{ matrix.builder }}
          path: ${{ github.workspace }}/install
